# Requires docker-compose >= 1.29.0
version: '3.9'

services:
  gw-readonly:
    container_name: gw-mainnet_v1-readonly
    image: ghcr.io/nervosnetwork/godwoken-prebuilds:1.2.2-rc1
    expose: [8119, 8219]
    # healthcheck:
    #   test: /healthcheck.sh
    #   start_period: 10s
    #   interval: 30s
    #   retries: 100000
    working_dir: /deploy
    volumes:
    - ./chain-data/readonly/:/mnt/
    - ./gw-mainnet_v1-config-readonly.toml:/deploy/config.toml
    - ./db.toml:/deploy/db.toml:ro
    - ./mock.key:/deploy/zero.key:ro
    # - ./healthcheck.sh:/healthcheck.sh:ro
    environment:
    # other log envs: ,gw_generator=debug,gw_chain=debug
    - RUST_LOG=info
    command: godwoken
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
