node_mode = 'readonly'

# Note: It is better to run your own CKB mainnet node.
# see: https://docs.nervos.org/docs/basics/guides/run-ckb-with-docker/#run-a-ckb-mainnet-node
[rpc_client]
ckb_url = 'https://mainnet.ckb.dev/rpc'

[rpc_server]
listen = '0.0.0.0:8119'
enable_methods = []

# The P2P syncing feature could improve the experience of an external Godwoken readonly node.
# An external Godwoken readonly node can receive layer-2 block sync messages from fullnode through
# the configured p2p_network.
#
# see also: https://github.com/godwokenrises/godwoken/blob/develop/docs/p2p_sync.md
[p2p_network_config]
dial = ["/dns4/mainnet.p2p.godwoken.io/tcp/9999"]

# builtin consensus config
# see https://github.com/godwokenrises/godwoken/pull/946
[consensus]
# https://github.com/godwokenrises/godwoken/blob/develop/crates/config/src/consensus/builtins/mainnet.toml
builtin = 'Mainnet'

[debug]
output_l1_tx_cycles = true
expected_l1_tx_upper_bound_cycles = 350000000
debug_tx_dump_path = '/mnt/debug-tx-dump'
enable_debug_rpc = false

[block_producer]
check_mem_block_before_submit = false

[block_producer.block_producer]
address_type = "Eth"
address = '0xb8cde090e6a4741b6450308fad1dc338c53936a0'

[block_producer.challenger_config.rewards_receiver_lock]
code_hash = '0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8'
hash_type = 'type'
args = '0x65c41e085ce5edfc7013ae7191635b3888f155c9'

[mem_pool]
execute_l2tx_max_cycles = 3000000000
restore_path = '/mnt/mem-pool/mem-block'
[mem_pool.mem_block]
max_deposits = 50
max_withdrawals = 50
# MAX_TPS * block_time = 40 * 8 = 320, rounded up to 400
max_txs = 400
# Introduce max_cycles_limit of a Godwoken block
# https://github.com/nervosnetwork/godwoken/pull/767
max_cycles_limit = '1950000000'

# [mem_pool.mem_block.syscall_cycles]
# Default SyscallCyclesConfig:
# https://github.com/godwokenrises/godwoken/blob/v1.7.0/crates/config/src/config.rs#L579-L599


[store]
path = '/mnt/mainnet_v1-store.db'
options_file = '/deploy/db.toml'
cache_size = 536870912

[mem_pool.fee]
meta_cycles_limit = 20000
sudt_cycles_limit = 20000
eth_addr_reg_cycles_limit = 20000
withdraw_cycles_limit = 20000

[mem_pool.extra]
allowed_sudt_proxy_creator_account_id = [3]
sudt_proxy_code_hashes = ["0xde4542f5a5bd32c09cd98e9752281f88900a059aab7ac103edd9df214f136c52"]
